---
title: "Approximate Bayesian computation"
output:
  pdf_document: default
  html_document:
    df_print: paged
vignette: >
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Approximate Bayesian Computation (ABC)

You can perform parallel execution and subsequent ABC. See scripts/prmEst.ABC/abc.\* in the gitHub repository for the scripts and examples.

## Scripts

### For parallele execution

-   **abc.a.XX_make_list.R**: Make a job list

-   **abc.b_run\_{parallel, qsub}.sh**: Run the jobs in parallel with GNU parallel or qsub

### For abc() of library abc

-   **abc.c_make_data.R**: Make data for ABC from simulation results

-   **abc.d_exec_calc.R**: Calculate ABC from the ABC data

## Example

```         
# First ABC round
# You need to have Input/ and R/ here.
# You need to chmod abc.run{,_qsub}.sh to be executable.
# You may need to change the newline code (for Linux's or Win's) of abc.*.
cp scripts/ABC/abc.*.{sh,R} .
cp -a inst/extdata/Test1/Input .
Rscript abc.a.01_make_list.R abc.01_config.R
bash abc.b_run_parallel.sh
Rscript abc.c_make_data.R abc.01_config.R
Rscript abc.d_exec_calc.R abc.01_config.R

# Second ABC round, using parameters selected by the first ABC
Rscript abc.a.02_make_list.R abc.02_config.R
bash abc.b_run_parallel.sh
Rscript abc.c_make_data.R abc.02_config.R
Rscript abc.d_exec_calc.R abc.02_config.R
```

## abc.a.XX_make_list.R

### Inputs

-   `abc.XX_config.R`: Configuration file explained below in **ABC configuration file**.

-   Internally uses a script specified by `run_script`, such as `abc.01_run.R`, in the configuration file.

    -   This script is run in parallel. Change this script according to your purpose.

-   Internally uses `abc.run{,_qsub}.sh`.

### Outputs

-   `run_list.txt`: Job list
-   `work/*/`: Output directory for parallel execution. Can change this name in the configuration file.
    -   Under this directory, replications are made as `000001/`, `000002/`, ...

## abc.b_run\_{parallel, qsub}.sh

### Input

-   Internally uses `run_list.txt`.

### Outputs

-   Simulation outputs are output under the replication directories under `work/*/`.
-   `log/`: Log directory

### Notes

-   This script is simple. You may need to change option parameters written in this script (especially, \_qsub.sh) for parallel computation.

## abc.c_make_data.R and abc.d_exec_calc.R

### Input

-   `abc.XX_config.R`: Configuration file explained below in **ABC configuration file**.

### Outputs

-   Described below in **ABC output directory**.

## ABC configuration file

\# Environment setting

-   base_dir: your working directory.

### For parallel execution

-   replicates: number of replications to simulate

-   work_dir: output directory for parallel execution

-   run_script: this script will be run in parallel with Input/ and R/.

### For ABC

\# Output

-   ABC_dir: output directory for ABC results, as described below in **ABC output directory**.

\# Simulation VAFs

-   VAF_files_glob: glob pattern to get simulation VAFs

\# Observation VAFs

-   rint_file: path to samples.Rint.txt

-   rother_file: path to samples.Rother.txt

-   rother_regex: regular expression to select other regions/genes from rother_file

-   samples: sample IDs to select samples from rint_file and rother_file

-   sample_cols: column numbers to indicate sample, gene, and vaf in rint_file and rother_file

\# Parameters for simulation results

-   tumor_contents: assumed tumor contents

-   min_vaf: VAFs below this value are ignored as LOD (limit of detection).

\# Parameters for ABC

-   abc.tol: tolerance rate of abc() in library abc

-   abc.method: ABC method of abc() in library abc

\# Inputs for next round ABC

-   seleted_file: path to an output file, TOLSel\_..., which lists simulation replications selected by ABC.

    -   See below **ABC output directory**.

-   generator_dir: path to the directory where the selected replications exist.

    -   From this directory, the selected replications are copied in the bootstrap method to be ready for next round ABC.

### Example 1

```         
## Your working directory with R/, Input/, and abc.run{,_qsub}.sh. 
base_dir <- './'


## For parallele execution ======================================
replicates <- 5
work_dir <- "./work/first"
run_script <- './abc.01.run.R'


## For ABC ======================================================
## Output
ABC_dir <- './ABC1'

## Sim VAFs
VAF_files_glob <- 'work/first/*/Output/VAF/VAF.txt'

## Obs VAFs
rint_file    <- 'Input/Samples/samples.Rint.txt'
rother_file  <- 'Input/Samples/samples.Rother.txt'
rother_regex <- "^_.*"
samples      <- c('TCGA-AZ-6608-01A-11D-1835-10')
sample_cols  <- c(6, 1, 11) ## sample, gene, vaf

##
tumor_contents <- c(1.00, 0.8, 0.6, 0.4)
min_vaf        <- 0.1

##
abc.tol    <- 0.1
abc.method <- 'rejection'
```

### Example 2

```         
## Similar to the example above
...

## Selection based on ABC
selected_file <- 'ABC1/TCGA-AZ-6608-01A-11D-1835-10/TOLSel_rejection_tumor_content=0.40_tol=0.100.txt'
generator_dir <- 'work/first/%06d'
```

## ABC output directory

-   Outputs by abc.c_make_data.R

```         
<ABC>/<Sample Name>:
- param_mat.txt: Parameters        , data for abc() of library abc
- sumstat_*.txt: Summary statistics, data for abc() of library abc
- target_*.txt:  Target            , data for abc() of library abc
```

-   Outputs by abc.d_exec_calc.R

```         
<ABC>/<Sample Name>: 
- TOLSel_rejection_*.txt: Selected simulation replications,         by abc()
- ABC_dist_*.txt: Distance between observation and each simulation, by abc()
```

## Bayesian optimization

To obtain a point estimate from a joint posterior distribution implied by points selected through ABC, scripts/prmEst.BayesianOptim/\* in the gitHub repository may be useful.

The scripts estimate the optimal point (a combination of parameter values) with shortest ABC distance.
